/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.api;

import com.verbatim.client.spring_rest.models.AckResponse;
import com.verbatim.client.spring_rest.models.DocumentDownloadUrl;
import com.verbatim.client.spring_rest.models.DocumentPreviewUrls;
import com.verbatim.client.spring_rest.models.Error;
import com.verbatim.client.spring_rest.models.Post;
import com.verbatim.client.spring_rest.models.PostAttachmentResponse;
import com.verbatim.client.spring_rest.models.PostItemResponse;
import com.verbatim.client.spring_rest.models.PostListResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostApi
 */
@Disabled
class PostApiTest {

    private final PostApi api = new PostApi();

    
    /**
     * Attachments from a post
     *
     * List the attachments from a post.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void attachmentTest() {
        UUID postId = null;

        PostAttachmentResponse response = api.attachment(postId);

        // TODO: test validations
    }
    
    /**
     * Delete a post
     *
     * Permanently delete a post and its attachments. Documents and embeddings referenced by the attachments are **not** affected.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void delete3Test() {
        UUID postId = null;

        AckResponse response = api.delete3(postId);

        // TODO: test validations
    }
    
    /**
     * Get a presigned download URL
     *
     * Return a time-limited presigned URL the client can use to GET the document content directly from the storage backend (S3) — no content flows through this server.  The URL is bound to the document&#39;s content type; clients SHOULD use the returned &#x60;filename&#x60; for the local save name. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void downloadUrlTest() {
        UUID docId = null;

        DocumentDownloadUrl response = api.downloadUrl(docId);

        // TODO: test validations
    }
    
    /**
     * Get a post
     *
     * Fetch a single post by its identifier, including its attachments.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void get3Test() {
        UUID postId = null;

        Post response = api.get3(postId);

        // TODO: test validations
    }
    
    /**
     * List posts
     *
     * Paginate every post (user queries and system answers) in a session, newest first.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void list2Test() {
        UUID sessionId = null;
        Integer pageSize = null;
        Integer pageIndex = null;

        PostListResponse response = api.list2(sessionId, pageSize, pageIndex);

        // TODO: test validations
    }
    
    /**
     * Get presigned preview URLs
     *
     * Return time-limited presigned URLs for the rendered preview images of the document. One entry is issued per (page, size): by default the first 4 pages × {SMALL, MEDIUM}, so up to 8 entries per call.  Pass &#x60;pages&#x60; to restrict the response to specific page indices (e.g. &#x60;pages&#x3D;0&amp;pages&#x3D;2&#x60;). When omitted, pages 0–3 are used. Duplicate values are preserved as supplied.  The URLs point at preview images produced asynchronously by the rendering pipeline. No existence check is performed — individual URLs MAY return 404 when fetched if the corresponding (page, size) hasn&#39;t been generated yet; clients SHOULD fall back per-tile. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void previewUrlsTest() {
        UUID docId = null;
        List<Integer> pages = null;

        DocumentPreviewUrls response = api.previewUrls(docId, pages);

        // TODO: test validations
    }
    
    /**
     * Send a query
     *
     * Submit a user message to a session and run the full RAG pipeline:  1. Persist the query as a post with &#x60;owner &#x3D; USER&#x60;. 2. Vectorize the query and run a cosine-similarity search against the session&#39;s corpora. 3. Feed the top chunks to the session&#39;s LLM as context. 4. Persist the answer as a post with &#x60;owner &#x3D; SYSTEM&#x60;, with attachments pointing to the chunks used.  The response contains both the user post (&#x60;query&#x60;) and the system post (&#x60;answer&#x60;). 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void queryTest() {
        UUID sessionId = null;
        String body = null;
        String lang = null;

        PostItemResponse response = api.query(sessionId, body, lang);

        // TODO: test validations
    }
    
}
