/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.api;

import com.verbatim.client.spring_rest.models.AckResponse;
import com.verbatim.client.spring_rest.models.Error;
import com.verbatim.client.spring_rest.models.Session;
import com.verbatim.client.spring_rest.models.SessionCreateRequest;
import com.verbatim.client.spring_rest.models.SessionCreateResponse;
import com.verbatim.client.spring_rest.models.SessionListResponse;
import com.verbatim.client.spring_rest.models.SessionUpdateRequest;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SessionApi
 */
@Disabled
class SessionApiTest {

    private final SessionApi api = new SessionApi();

    
    /**
     * Create a session
     *
     * Open a new conversation session against one or more corpora. The session is attached to the user carried by the caller&#39;s JWT. The model, system prompt, temperature and thinking flag are locked at creation time and apply to every post in the session.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void createTest() {
        SessionCreateRequest sessionCreateRequest = null;

        SessionCreateResponse response = api.create(sessionCreateRequest);

        // TODO: test validations
    }
    
    /**
     * Delete a session
     *
     * Soft-delete a session. **Cascades** to every post in the session (also soft-deleted). Documents and embeddings are **not** affected.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void deleteTest() {
        UUID sessionId = null;

        AckResponse response = api.delete(sessionId);

        // TODO: test validations
    }
    
    /**
     * Get a session
     *
     * Fetch a session&#39;s metadata (user, corpora, model, system prompt, parameters). Use &#x60;GET /v1/post&#x60; to retrieve its posts.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getTest() {
        UUID sessionId = null;

        Session response = api.get(sessionId);

        // TODO: test validations
    }
    
    /**
     * List sessions attached to a corpus
     *
     * Paginate the sessions opened against a corpus, newest first. The corpus must belong to the caller&#39;s organization.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void list1Test() {
        UUID corpusId = null;
        Integer pageSize = null;
        Integer pageIndex = null;

        SessionListResponse response = api.list1(corpusId, pageSize, pageIndex);

        // TODO: test validations
    }
    
    /**
     * List sessions matching a metadata fragment
     *
     * Paginate sessions whose metadata JSONB *contains* the provided fragment (PostgreSQL &#x60;@&gt;&#x60; operator). Results are scoped to the caller&#39;s organization. Filtering on a single key/value pair: pass &#x60;key&#x60; and &#x60;value&#x60;. For richer filtering (nested JSON, multiple keys) pass a raw JSON object as &#x60;json&#x60;.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void listByMetadataTest() {
        String key = null;
        String value = null;
        String json = null;
        Integer pageSize = null;
        Integer pageIndex = null;

        SessionListResponse response = api.listByMetadata(key, value, json, pageSize, pageIndex);

        // TODO: test validations
    }
    
    /**
     * List every session in the caller&#39;s organization
     *
     * Paginate every session attached to at least one corpus of the caller&#39;s organization, newest first. The organization is resolved from the JWT, no parameter is needed.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void listByOrganizationTest() {
        Integer pageSize = null;
        Integer pageIndex = null;

        SessionListResponse response = api.listByOrganization(pageSize, pageIndex);

        // TODO: test validations
    }
    
    /**
     * List sessions owned by a user
     *
     * Paginate the sessions opened by a given user identifier, newest first. Results are scoped to the caller&#39;s organization at the SQL level: only sessions attached to at least one corpus of the caller&#39;s org are returned, so a user identifier shared across tenants never leaks rows. Pass &#x60;corpusId&#x60; to further restrict results to sessions bound to that specific corpus.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void listByUserTest() {
        String userId = null;
        UUID corpusId = null;
        Integer pageSize = null;
        Integer pageIndex = null;

        SessionListResponse response = api.listByUser(userId, corpusId, pageSize, pageIndex);

        // TODO: test validations
    }
    
    /**
     * Update a session
     *
     * Patch one or more session attributes. Only the fields provided in the request body are updated; omitted fields keep their current value. Returns the full updated session.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void updateTest() {
        UUID sessionId = null;
        SessionUpdateRequest sessionUpdateRequest = null;

        Session response = api.update(sessionId, sessionUpdateRequest);

        // TODO: test validations
    }
    
}
