/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AccessTokenCreateRequest
 */
@JsonPropertyOrder({
  AccessTokenCreateRequest.JSON_PROPERTY_TTL,
  AccessTokenCreateRequest.JSON_PROPERTY_ISSUER,
  AccessTokenCreateRequest.JSON_PROPERTY_EMAIL,
  AccessTokenCreateRequest.JSON_PROPERTY_USER_ID,
  AccessTokenCreateRequest.JSON_PROPERTY_SCOPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AccessTokenCreateRequest {
  public static final String JSON_PROPERTY_TTL = "ttl";
  @javax.annotation.Nullable
  private Long ttl;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  @javax.annotation.Nullable
  private String issuer;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private List<String> scope = new ArrayList<>();

  public AccessTokenCreateRequest() {
  }

  public AccessTokenCreateRequest ttl(@javax.annotation.Nullable Long ttl) {
    
    this.ttl = ttl;
    return this;
  }

  /**
   * Token validity in seconds. Defaults to 3600 (1 hour).
   * minimum: 1
   * @return ttl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TTL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTtl() {
    return ttl;
  }


  @JsonProperty(value = JSON_PROPERTY_TTL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTtl(@javax.annotation.Nullable Long ttl) {
    this.ttl = ttl;
  }

  public AccessTokenCreateRequest issuer(@javax.annotation.Nullable String issuer) {
    
    this.issuer = issuer;
    return this;
  }

  /**
   * Optional label identifying the system that requested the token.
   * @return issuer
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
  }

  public AccessTokenCreateRequest email(@javax.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Optional email of the end-user the token is issued for.
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }

  public AccessTokenCreateRequest userId(@javax.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Optional user identifier.
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }

  public AccessTokenCreateRequest scope(@javax.annotation.Nullable List<String> scope) {
    
    this.scope = scope;
    return this;
  }

  public AccessTokenCreateRequest addScopeItem(String scopeItem) {
    if (this.scope == null) {
      this.scope = new ArrayList<>();
    }
    this.scope.add(scopeItem);
    return this;
  }

  /**
   * Optional list of permission scopes to associate with the token. Pattern is DOMAIN:ACTION, where DOMAIN must be one of the values [doc|corpus|session|post|config] and ACTION one of the values [create|read|update|delete]
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable List<String> scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenCreateRequest accessTokenCreateRequest = (AccessTokenCreateRequest) o;
    return Objects.equals(this.ttl, accessTokenCreateRequest.ttl) &&
        Objects.equals(this.issuer, accessTokenCreateRequest.issuer) &&
        Objects.equals(this.email, accessTokenCreateRequest.email) &&
        Objects.equals(this.userId, accessTokenCreateRequest.userId) &&
        Objects.equals(this.scope, accessTokenCreateRequest.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ttl, issuer, email, userId, scope);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenCreateRequest {\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

