/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * A file ingested into a corpus. Holds metadata; the binary content is streamed via the download endpoint.
 */
@JsonPropertyOrder({
  Document.JSON_PROPERTY_ID,
  Document.JSON_PROPERTY_CORPUS_ID,
  Document.JSON_PROPERTY_USER_ID,
  Document.JSON_PROPERTY_FILENAME,
  Document.JSON_PROPERTY_CONTENT_TYPE,
  Document.JSON_PROPERTY_STATUS,
  Document.JSON_PROPERTY_PATH,
  Document.JSON_PROPERTY_PROVIDER,
  Document.JSON_PROPERTY_LANG,
  Document.JSON_PROPERTY_METADATA,
  Document.JSON_PROPERTY_DOC_CREATE,
  Document.JSON_PROPERTY_DOC_UPDATE,
  Document.JSON_PROPERTY_CREATED_AT,
  Document.JSON_PROPERTY_UPDATED_AT,
  Document.JSON_PROPERTY_SIZE,
  Document.JSON_PROPERTY_TOKENS,
  Document.JSON_PROPERTY_NB_WORDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Document {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_CORPUS_ID = "corpusId";
  @javax.annotation.Nonnull
  private String corpusId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @javax.annotation.Nonnull
  private String filename;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "contentType";
  @javax.annotation.Nonnull
  private String contentType;

  /**
   * Lifecycle status of the document. AWAITING_UPLOAD: created via init, file not yet uploaded. READY: ingestion completed.
   */
  public enum StatusEnum {
    AWAITING_UPLOAD(String.valueOf("AWAITING_UPLOAD")),
    
    PENDING(String.valueOf("PENDING")),
    
    PROCESSING(String.valueOf("PROCESSING")),
    
    READY(String.valueOf("READY")),
    
    FAILED(String.valueOf("FAILED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @javax.annotation.Nullable
  private String provider;

  public static final String JSON_PROPERTY_LANG = "lang";
  @javax.annotation.Nullable
  private String lang;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_DOC_CREATE = "docCreate";
  @javax.annotation.Nullable
  private OffsetDateTime docCreate;

  public static final String JSON_PROPERTY_DOC_UPDATE = "docUpdate";
  @javax.annotation.Nullable
  private OffsetDateTime docUpdate;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_SIZE = "size";
  @javax.annotation.Nullable
  private Long size;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @javax.annotation.Nullable
  private Integer tokens;

  public static final String JSON_PROPERTY_NB_WORDS = "nbWords";
  @javax.annotation.Nullable
  private Integer nbWords;

  public Document() {
  }

  public Document id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the document (UUIDv4).
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public Document corpusId(@javax.annotation.Nonnull String corpusId) {
    
    this.corpusId = corpusId;
    return this;
  }

  /**
   * ID of the corpus this document belongs to.
   * @return corpusId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CORPUS_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCorpusId() {
    return corpusId;
  }


  @JsonProperty(value = JSON_PROPERTY_CORPUS_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCorpusId(@javax.annotation.Nonnull String corpusId) {
    this.corpusId = corpusId;
  }

  public Document userId(@javax.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Identifier of the user who uploaded the document. May be null when no user identity was provided at upload time.
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }

  public Document filename(@javax.annotation.Nonnull String filename) {
    
    this.filename = filename;
    return this;
  }

  /**
   * Original filename, as provided at upload time.
   * @return filename
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFilename() {
    return filename;
  }


  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFilename(@javax.annotation.Nonnull String filename) {
    this.filename = filename;
  }

  public Document contentType(@javax.annotation.Nonnull String contentType) {
    
    this.contentType = contentType;
    return this;
  }

  /**
   * MIME content type of the file.
   * @return contentType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContentType() {
    return contentType;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
  }

  public Document status(@javax.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Lifecycle status of the document. AWAITING_UPLOAD: created via init, file not yet uploaded. READY: ingestion completed.
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public Document path(@javax.annotation.Nullable String path) {
    
    this.path = path;
    return this;
  }

  /**
   * Internal storage path of the file. Opaque — use the download endpoint instead.
   * @return path
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@javax.annotation.Nullable String path) {
    this.path = path;
  }

  public Document provider(@javax.annotation.Nullable String provider) {
    
    this.provider = provider;
    return this;
  }

  /**
   * Free-form label identifying the source of the document.
   * @return provider
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }

  public Document lang(@javax.annotation.Nullable String lang) {
    
    this.lang = lang;
    return this;
  }

  /**
   * ISO-639 language code used during ingestion.
   * @return lang
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LANG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLang() {
    return lang;
  }


  @JsonProperty(value = JSON_PROPERTY_LANG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLang(@javax.annotation.Nullable String lang) {
    this.lang = lang;
  }

  public Document metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public Document putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Arbitrary JSON metadata attached to the document. Stored as JSONB.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }

  public Document docCreate(@javax.annotation.Nullable OffsetDateTime docCreate) {
    
    this.docCreate = docCreate;
    return this;
  }

  /**
   * Original creation date of the source document (ISO-8601, UTC). Falls back to upload time when unknown.
   * @return docCreate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOC_CREATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDocCreate() {
    return docCreate;
  }


  @JsonProperty(value = JSON_PROPERTY_DOC_CREATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocCreate(@javax.annotation.Nullable OffsetDateTime docCreate) {
    this.docCreate = docCreate;
  }

  public Document docUpdate(@javax.annotation.Nullable OffsetDateTime docUpdate) {
    
    this.docUpdate = docUpdate;
    return this;
  }

  /**
   * Original last-modified date of the source document (ISO-8601, UTC). Falls back to upload time when unknown.
   * @return docUpdate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOC_UPDATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDocUpdate() {
    return docUpdate;
  }


  @JsonProperty(value = JSON_PROPERTY_DOC_UPDATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocUpdate(@javax.annotation.Nullable OffsetDateTime docUpdate) {
    this.docUpdate = docUpdate;
  }

  public Document createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Date the document was uploaded to the platform (ISO-8601, UTC).
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Document updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Last update timestamp of the document row (ISO-8601, UTC).
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Document size(@javax.annotation.Nullable Long size) {
    
    this.size = size;
    return this;
  }

  /**
   * Size of the source file in bytes. Set after ingestion.
   * @return size
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSize() {
    return size;
  }


  @JsonProperty(value = JSON_PROPERTY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(@javax.annotation.Nullable Long size) {
    this.size = size;
  }

  public Document tokens(@javax.annotation.Nullable Integer tokens) {
    
    this.tokens = tokens;
    return this;
  }

  /**
   * Number of LLM tokens consumed to produce the summary. Set after ingestion.
   * @return tokens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTokens() {
    return tokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokens(@javax.annotation.Nullable Integer tokens) {
    this.tokens = tokens;
  }

  public Document nbWords(@javax.annotation.Nullable Integer nbWords) {
    
    this.nbWords = nbWords;
    return this;
  }

  /**
   * Number of words in the source document. Set after ingestion.
   * @return nbWords
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NB_WORDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNbWords() {
    return nbWords;
  }


  @JsonProperty(value = JSON_PROPERTY_NB_WORDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNbWords(@javax.annotation.Nullable Integer nbWords) {
    this.nbWords = nbWords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.id, document.id) &&
        Objects.equals(this.corpusId, document.corpusId) &&
        Objects.equals(this.userId, document.userId) &&
        Objects.equals(this.filename, document.filename) &&
        Objects.equals(this.contentType, document.contentType) &&
        Objects.equals(this.status, document.status) &&
        Objects.equals(this.path, document.path) &&
        Objects.equals(this.provider, document.provider) &&
        Objects.equals(this.lang, document.lang) &&
        Objects.equals(this.metadata, document.metadata) &&
        Objects.equals(this.docCreate, document.docCreate) &&
        Objects.equals(this.docUpdate, document.docUpdate) &&
        Objects.equals(this.createdAt, document.createdAt) &&
        Objects.equals(this.updatedAt, document.updatedAt) &&
        Objects.equals(this.size, document.size) &&
        Objects.equals(this.tokens, document.tokens) &&
        Objects.equals(this.nbWords, document.nbWords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, corpusId, userId, filename, contentType, status, path, provider, lang, metadata, docCreate, docUpdate, createdAt, updatedAt, size, tokens, nbWords);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    docCreate: ").append(toIndentedString(docCreate)).append("\n");
    sb.append("    docUpdate: ").append(toIndentedString(docUpdate)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    nbWords: ").append(toIndentedString(nbWords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

