/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.spring_rest.models.Document;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paginated list of documents in a corpus.
 */
@JsonPropertyOrder({
  DocumentListResponse.JSON_PROPERTY_CORPUS_ID,
  DocumentListResponse.JSON_PROPERTY_PAGE_INDEX,
  DocumentListResponse.JSON_PROPERTY_ITEMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class DocumentListResponse {
  public static final String JSON_PROPERTY_CORPUS_ID = "corpusId";
  @javax.annotation.Nonnull
  private String corpusId;

  public static final String JSON_PROPERTY_PAGE_INDEX = "pageIndex";
  @javax.annotation.Nonnull
  private Integer pageIndex = 0;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @javax.annotation.Nonnull
  private List<Document> items = new ArrayList<>();

  public DocumentListResponse() {
  }

  public DocumentListResponse corpusId(@javax.annotation.Nonnull String corpusId) {
    
    this.corpusId = corpusId;
    return this;
  }

  /**
   * ID of the corpus (UUIDv4).
   * @return corpusId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CORPUS_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCorpusId() {
    return corpusId;
  }


  @JsonProperty(value = JSON_PROPERTY_CORPUS_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCorpusId(@javax.annotation.Nonnull String corpusId) {
    this.corpusId = corpusId;
  }

  public DocumentListResponse pageIndex(@javax.annotation.Nonnull Integer pageIndex) {
    
    this.pageIndex = pageIndex;
    return this;
  }

  /**
   * Zero-based index of the returned page.
   * @return pageIndex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPageIndex() {
    return pageIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPageIndex(@javax.annotation.Nonnull Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public DocumentListResponse items(@javax.annotation.Nonnull List<Document> items) {
    
    this.items = items;
    return this;
  }

  public DocumentListResponse addItemsItem(Document itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Documents contained in this page, newest first.
   * @return items
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Document> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItems(@javax.annotation.Nonnull List<Document> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentListResponse documentListResponse = (DocumentListResponse) o;
    return Objects.equals(this.corpusId, documentListResponse.corpusId) &&
        Objects.equals(this.pageIndex, documentListResponse.pageIndex) &&
        Objects.equals(this.items, documentListResponse.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(corpusId, pageIndex, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentListResponse {\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

