/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.spring_rest.models.Post;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paginated list of posts in a session.
 */
@JsonPropertyOrder({
  PostListResponse.JSON_PROPERTY_SESSION_ID,
  PostListResponse.JSON_PROPERTY_PAGE_INDEX,
  PostListResponse.JSON_PROPERTY_ITEMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PostListResponse {
  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nonnull
  private UUID sessionId;

  public static final String JSON_PROPERTY_PAGE_INDEX = "pageIndex";
  @javax.annotation.Nullable
  private Integer pageIndex;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @javax.annotation.Nullable
  private List<Post> items = new ArrayList<>();

  public PostListResponse() {
  }

  public PostListResponse sessionId(@javax.annotation.Nonnull UUID sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * ID of the session (UUIDv4).
   * @return sessionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionId(@javax.annotation.Nonnull UUID sessionId) {
    this.sessionId = sessionId;
  }

  public PostListResponse pageIndex(@javax.annotation.Nullable Integer pageIndex) {
    
    this.pageIndex = pageIndex;
    return this;
  }

  /**
   * Zero-based index of the returned page.
   * @return pageIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageIndex() {
    return pageIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageIndex(@javax.annotation.Nullable Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public PostListResponse items(@javax.annotation.Nullable List<Post> items) {
    
    this.items = items;
    return this;
  }

  public PostListResponse addItemsItem(Post itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Posts contained in this page, newest first.
   * @return items
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Post> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(@javax.annotation.Nullable List<Post> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostListResponse postListResponse = (PostListResponse) o;
    return Objects.equals(this.sessionId, postListResponse.sessionId) &&
        Objects.equals(this.pageIndex, postListResponse.pageIndex) &&
        Objects.equals(this.items, postListResponse.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, pageIndex, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostListResponse {\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

