/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Patch a custom agent. Every field is optional; the ones you omit keep their current value.  Because an omitted field means \&quot;leave alone\&quot;, it cannot also mean \&quot;put this back to the platform default\&quot;. That is what &#x60;reset&#x60; is for: list the names of the nullable fields you want to un-set, and they go back to tracking the platform default instead of holding the value you gave them earlier. &#x60;reset&#x60; is applied after the rest of the body, so naming a field in both wins for &#x60;reset&#x60;.  Core agents (&#x60;lock: true&#x60;) are not writable — patching one answers &#x60;400&#x60;. 
 */
@JsonPropertyOrder({
  AgentUpdateRequest.JSON_PROPERTY_NAME,
  AgentUpdateRequest.JSON_PROPERTY_DESCRIPTION,
  AgentUpdateRequest.JSON_PROPERTY_TOP_K,
  AgentUpdateRequest.JSON_PROPERTY_RERANK,
  AgentUpdateRequest.JSON_PROPERTY_RERANK_TOP_K,
  AgentUpdateRequest.JSON_PROPERTY_CONTEXT,
  AgentUpdateRequest.JSON_PROPERTY_BEHAVIOUR,
  AgentUpdateRequest.JSON_PROPERTY_SPIRIT,
  AgentUpdateRequest.JSON_PROPERTY_USE_HISTORY,
  AgentUpdateRequest.JSON_PROPERTY_HISTORY_SIZE,
  AgentUpdateRequest.JSON_PROPERTY_THINKING_MODE,
  AgentUpdateRequest.JSON_PROPERTY_TEMPERATURE,
  AgentUpdateRequest.JSON_PROPERTY_RERANK_MODEL,
  AgentUpdateRequest.JSON_PROPERTY_BASE_MODEL,
  AgentUpdateRequest.JSON_PROPERTY_RESET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AgentUpdateRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_TOP_K = "topK";
  @javax.annotation.Nullable
  private Integer topK;

  public static final String JSON_PROPERTY_RERANK = "rerank";
  @javax.annotation.Nullable
  private Boolean rerank;

  public static final String JSON_PROPERTY_RERANK_TOP_K = "rerankTopK";
  @javax.annotation.Nullable
  private Integer rerankTopK;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  @javax.annotation.Nullable
  private String context;

  public static final String JSON_PROPERTY_BEHAVIOUR = "behaviour";
  @javax.annotation.Nullable
  private String behaviour;

  public static final String JSON_PROPERTY_SPIRIT = "spirit";
  @javax.annotation.Nullable
  private String spirit;

  public static final String JSON_PROPERTY_USE_HISTORY = "useHistory";
  @javax.annotation.Nullable
  private Boolean useHistory;

  public static final String JSON_PROPERTY_HISTORY_SIZE = "historySize";
  @javax.annotation.Nullable
  private Integer historySize;

  /**
   * Reasoning budget the model spends before answering.
   */
  public enum ThinkingModeEnum {
    LOW(String.valueOf("LOW")),
    
    HIGH(String.valueOf("HIGH"));

    private String value;

    ThinkingModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ThinkingModeEnum fromValue(String value) {
      for (ThinkingModeEnum b : ThinkingModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_THINKING_MODE = "thinkingMode";
  @javax.annotation.Nullable
  private ThinkingModeEnum thinkingMode;

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @javax.annotation.Nullable
  private Double temperature;

  public static final String JSON_PROPERTY_RERANK_MODEL = "rerankModel";
  @javax.annotation.Nullable
  private String rerankModel;

  public static final String JSON_PROPERTY_BASE_MODEL = "baseModel";
  @javax.annotation.Nullable
  private String baseModel;

  public static final String JSON_PROPERTY_RESET = "reset";
  @javax.annotation.Nullable
  private List<String> reset = new ArrayList<>();

  public AgentUpdateRequest() {
  }

  public AgentUpdateRequest name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Human-readable name of the agent. Max 128 characters. Renaming onto a name another of your agents holds, or one a platform agent (&#x60;lock: true&#x60;) carries, answers &#x60;409&#x60;. Re-sending this agent&#39;s own current name is not a rename and is never a conflict.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public AgentUpdateRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Free-form description of what this agent is for.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public AgentUpdateRequest topK(@javax.annotation.Nullable Integer topK) {
    
    this.topK = topK;
    return this;
  }

  /**
   * Chunks the vector search returns, before re-ranking narrows them down.
   * minimum: 1
   * @return topK
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_K, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTopK() {
    return topK;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_K, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopK(@javax.annotation.Nullable Integer topK) {
    this.topK = topK;
  }

  public AgentUpdateRequest rerank(@javax.annotation.Nullable Boolean rerank) {
    
    this.rerank = rerank;
    return this;
  }

  /**
   * Whether retrieved chunks are re-ranked by an LLM before the answer is generated.
   * @return rerank
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRerank() {
    return rerank;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerank(@javax.annotation.Nullable Boolean rerank) {
    this.rerank = rerank;
  }

  public AgentUpdateRequest rerankTopK(@javax.annotation.Nullable Integer rerankTopK) {
    
    this.rerankTopK = rerankTopK;
    return this;
  }

  /**
   * Chunks kept after re-ranking.
   * minimum: 1
   * @return rerankTopK
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANK_TOP_K, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRerankTopK() {
    return rerankTopK;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANK_TOP_K, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerankTopK(@javax.annotation.Nullable Integer rerankTopK) {
    this.rerankTopK = rerankTopK;
  }

  public AgentUpdateRequest context(@javax.annotation.Nullable String context) {
    
    this.context = context;
    return this;
  }

  /**
   * First third of the system instruction — what the model is looking at.
   * @return context
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContext() {
    return context;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(@javax.annotation.Nullable String context) {
    this.context = context;
  }

  public AgentUpdateRequest behaviour(@javax.annotation.Nullable String behaviour) {
    
    this.behaviour = behaviour;
    return this;
  }

  /**
   * Second third of the system instruction — how the model should act.
   * @return behaviour
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BEHAVIOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBehaviour() {
    return behaviour;
  }


  @JsonProperty(value = JSON_PROPERTY_BEHAVIOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBehaviour(@javax.annotation.Nullable String behaviour) {
    this.behaviour = behaviour;
  }

  public AgentUpdateRequest spirit(@javax.annotation.Nullable String spirit) {
    
    this.spirit = spirit;
    return this;
  }

  /**
   * Last third of the system instruction — the tone it should take.
   * @return spirit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPIRIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpirit() {
    return spirit;
  }


  @JsonProperty(value = JSON_PROPERTY_SPIRIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpirit(@javax.annotation.Nullable String spirit) {
    this.spirit = spirit;
  }

  public AgentUpdateRequest useHistory(@javax.annotation.Nullable Boolean useHistory) {
    
    this.useHistory = useHistory;
    return this;
  }

  /**
   * When &#x60;false&#x60;, previous posts of the session are not replayed.
   * @return useHistory
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USE_HISTORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseHistory() {
    return useHistory;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_HISTORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseHistory(@javax.annotation.Nullable Boolean useHistory) {
    this.useHistory = useHistory;
  }

  public AgentUpdateRequest historySize(@javax.annotation.Nullable Integer historySize) {
    
    this.historySize = historySize;
    return this;
  }

  /**
   * Number of trailing posts replayed.
   * minimum: 1
   * @return historySize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HISTORY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHistorySize() {
    return historySize;
  }


  @JsonProperty(value = JSON_PROPERTY_HISTORY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHistorySize(@javax.annotation.Nullable Integer historySize) {
    this.historySize = historySize;
  }

  public AgentUpdateRequest thinkingMode(@javax.annotation.Nullable ThinkingModeEnum thinkingMode) {
    
    this.thinkingMode = thinkingMode;
    return this;
  }

  /**
   * Reasoning budget the model spends before answering.
   * @return thinkingMode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THINKING_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ThinkingModeEnum getThinkingMode() {
    return thinkingMode;
  }


  @JsonProperty(value = JSON_PROPERTY_THINKING_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThinkingMode(@javax.annotation.Nullable ThinkingModeEnum thinkingMode) {
    this.thinkingMode = thinkingMode;
  }

  public AgentUpdateRequest temperature(@javax.annotation.Nullable Double temperature) {
    
    this.temperature = temperature;
    return this;
  }

  /**
   * Model temperature. Temperature must match model range.
   * minimum: 0
   * maximum: 1
   * @return temperature
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTemperature() {
    return temperature;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemperature(@javax.annotation.Nullable Double temperature) {
    this.temperature = temperature;
  }

  public AgentUpdateRequest rerankModel(@javax.annotation.Nullable String rerankModel) {
    
    this.rerankModel = rerankModel;
    return this;
  }

  /**
   * Model used for re-ranking. Must be one of the names &#x60;GET /v1/config/model&#x60; advertises.
   * @return rerankModel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANK_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRerankModel() {
    return rerankModel;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANK_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerankModel(@javax.annotation.Nullable String rerankModel) {
    this.rerankModel = rerankModel;
  }

  public AgentUpdateRequest baseModel(@javax.annotation.Nullable String baseModel) {
    
    this.baseModel = baseModel;
    return this;
  }

  /**
   * Model used to generate the answer. Must be one of the names &#x60;GET /v1/config/model&#x60; advertises.
   * @return baseModel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BASE_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseModel() {
    return baseModel;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseModel(@javax.annotation.Nullable String baseModel) {
    this.baseModel = baseModel;
  }

  public AgentUpdateRequest reset(@javax.annotation.Nullable List<String> reset) {
    
    this.reset = reset;
    return this;
  }

  public AgentUpdateRequest addResetItem(String resetItem) {
    if (this.reset == null) {
      this.reset = new ArrayList<>();
    }
    this.reset.add(resetItem);
    return this;
  }

  /**
   * Fields to un-set, so they go back to tracking the platform default. Only the nullable fields can be reset; anything else answers &#x60;400&#x60;. Applied after the rest of the body.
   * @return reset
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getReset() {
    return reset;
  }


  @JsonProperty(value = JSON_PROPERTY_RESET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReset(@javax.annotation.Nullable List<String> reset) {
    this.reset = reset;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentUpdateRequest agentUpdateRequest = (AgentUpdateRequest) o;
    return Objects.equals(this.name, agentUpdateRequest.name) &&
        Objects.equals(this.description, agentUpdateRequest.description) &&
        Objects.equals(this.topK, agentUpdateRequest.topK) &&
        Objects.equals(this.rerank, agentUpdateRequest.rerank) &&
        Objects.equals(this.rerankTopK, agentUpdateRequest.rerankTopK) &&
        Objects.equals(this.context, agentUpdateRequest.context) &&
        Objects.equals(this.behaviour, agentUpdateRequest.behaviour) &&
        Objects.equals(this.spirit, agentUpdateRequest.spirit) &&
        Objects.equals(this.useHistory, agentUpdateRequest.useHistory) &&
        Objects.equals(this.historySize, agentUpdateRequest.historySize) &&
        Objects.equals(this.thinkingMode, agentUpdateRequest.thinkingMode) &&
        Objects.equals(this.temperature, agentUpdateRequest.temperature) &&
        Objects.equals(this.rerankModel, agentUpdateRequest.rerankModel) &&
        Objects.equals(this.baseModel, agentUpdateRequest.baseModel) &&
        Objects.equals(this.reset, agentUpdateRequest.reset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, topK, rerank, rerankTopK, context, behaviour, spirit, useHistory, historySize, thinkingMode, temperature, rerankModel, baseModel, reset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentUpdateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    topK: ").append(toIndentedString(topK)).append("\n");
    sb.append("    rerank: ").append(toIndentedString(rerank)).append("\n");
    sb.append("    rerankTopK: ").append(toIndentedString(rerankTopK)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    behaviour: ").append(toIndentedString(behaviour)).append("\n");
    sb.append("    spirit: ").append(toIndentedString(spirit)).append("\n");
    sb.append("    useHistory: ").append(toIndentedString(useHistory)).append("\n");
    sb.append("    historySize: ").append(toIndentedString(historySize)).append("\n");
    sb.append("    thinkingMode: ").append(toIndentedString(thinkingMode)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    rerankModel: ").append(toIndentedString(rerankModel)).append("\n");
    sb.append("    baseModel: ").append(toIndentedString(baseModel)).append("\n");
    sb.append("    reset: ").append(toIndentedString(reset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

