/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Setup driving a RAG query: how wide the retrieval goes, whether results are re-ranked, what system instruction the model receives, how much history is replayed, and which models answer.  Two kinds of agent are returned by the same endpoints. **Core** agents belong to the platform, are visible to every organization and carry &#x60;lock: true&#x60; — they cannot be created, updated or deleted. **Custom** agents carry your &#x60;orgId&#x60;, &#x60;lock: false&#x60;, and are yours to manage.  Nullable fields are *overrides*, not copies. &#x60;null&#x60; means \&quot;use the platform default\&quot;, so a default that is retuned later moves every agent that never set one. &#x60;systemInstruction&#x60; is read-only and shows the instruction those resolved values actually produce. 
 */
@JsonPropertyOrder({
  Agent.JSON_PROPERTY_ID,
  Agent.JSON_PROPERTY_NAME,
  Agent.JSON_PROPERTY_DESCRIPTION,
  Agent.JSON_PROPERTY_LOCK,
  Agent.JSON_PROPERTY_TOP_K,
  Agent.JSON_PROPERTY_RERANK,
  Agent.JSON_PROPERTY_RERANK_TOP_K,
  Agent.JSON_PROPERTY_CONTEXT,
  Agent.JSON_PROPERTY_BEHAVIOUR,
  Agent.JSON_PROPERTY_SPIRIT,
  Agent.JSON_PROPERTY_USE_HISTORY,
  Agent.JSON_PROPERTY_HISTORY_SIZE,
  Agent.JSON_PROPERTY_THINKING_MODE,
  Agent.JSON_PROPERTY_TEMPERATURE,
  Agent.JSON_PROPERTY_RERANK_MODEL,
  Agent.JSON_PROPERTY_BASE_MODEL,
  Agent.JSON_PROPERTY_CREATED_AT,
  Agent.JSON_PROPERTY_UPDATED_AT,
  Agent.JSON_PROPERTY_DEFAULT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Agent {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_LOCK = "lock";
  @javax.annotation.Nonnull
  private Boolean lock;

  public static final String JSON_PROPERTY_TOP_K = "topK";
  @javax.annotation.Nonnull
  private Integer topK;

  public static final String JSON_PROPERTY_RERANK = "rerank";
  @javax.annotation.Nonnull
  private Boolean rerank;

  public static final String JSON_PROPERTY_RERANK_TOP_K = "rerankTopK";
  @javax.annotation.Nullable
  private Integer rerankTopK;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  @javax.annotation.Nullable
  private String context;

  public static final String JSON_PROPERTY_BEHAVIOUR = "behaviour";
  @javax.annotation.Nullable
  private String behaviour;

  public static final String JSON_PROPERTY_SPIRIT = "spirit";
  @javax.annotation.Nullable
  private String spirit;

  public static final String JSON_PROPERTY_USE_HISTORY = "useHistory";
  @javax.annotation.Nonnull
  private Boolean useHistory;

  public static final String JSON_PROPERTY_HISTORY_SIZE = "historySize";
  @javax.annotation.Nullable
  private Integer historySize;

  /**
   * Reasoning budget the model is asked to spend before answering.
   */
  public enum ThinkingModeEnum {
    LOW(String.valueOf("LOW")),
    
    HIGH(String.valueOf("HIGH"));

    private String value;

    ThinkingModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ThinkingModeEnum fromValue(String value) {
      for (ThinkingModeEnum b : ThinkingModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_THINKING_MODE = "thinkingMode";
  @javax.annotation.Nonnull
  private ThinkingModeEnum thinkingMode;

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @javax.annotation.Nullable
  private Double temperature;

  public static final String JSON_PROPERTY_RERANK_MODEL = "rerankModel";
  @javax.annotation.Nullable
  private String rerankModel;

  public static final String JSON_PROPERTY_BASE_MODEL = "baseModel";
  @javax.annotation.Nullable
  private String baseModel;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_DEFAULT = "default";
  @javax.annotation.Nonnull
  private Boolean _default;

  public Agent() {
  }

  public Agent id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the agent (UUIDv4).
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public Agent name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Human-readable name of the agent.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public Agent description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Free-form description of what this agent is for.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public Agent lock(@javax.annotation.Nonnull Boolean lock) {
    
    this.lock = lock;
    return this;
  }

  /**
   * Read-only. &#x60;true&#x60; for a core agent: shared across the platform and not writable. Attempting to update or delete one answers &#x60;400&#x60;.
   * @return lock
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLock() {
    return lock;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLock(@javax.annotation.Nonnull Boolean lock) {
    this.lock = lock;
  }

  public Agent topK(@javax.annotation.Nonnull Integer topK) {
    
    this.topK = topK;
    return this;
  }

  /**
   * Chunks the vector search returns, before re-ranking narrows them down.
   * @return topK
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOP_K, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTopK() {
    return topK;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_K, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTopK(@javax.annotation.Nonnull Integer topK) {
    this.topK = topK;
  }

  public Agent rerank(@javax.annotation.Nonnull Boolean rerank) {
    
    this.rerank = rerank;
    return this;
  }

  /**
   * Whether the retrieved chunks are re-ranked by an LLM before the answer is generated. Re-ranking also needs &#x60;rerankModel&#x60;; with none set the flag has nothing to run.
   * @return rerank
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RERANK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getRerank() {
    return rerank;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRerank(@javax.annotation.Nonnull Boolean rerank) {
    this.rerank = rerank;
  }

  public Agent rerankTopK(@javax.annotation.Nullable Integer rerankTopK) {
    
    this.rerankTopK = rerankTopK;
    return this;
  }

  /**
   * Chunks kept after re-ranking. &#x60;null&#x60; uses the platform default.
   * @return rerankTopK
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANK_TOP_K, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRerankTopK() {
    return rerankTopK;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANK_TOP_K, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerankTopK(@javax.annotation.Nullable Integer rerankTopK) {
    this.rerankTopK = rerankTopK;
  }

  public Agent context(@javax.annotation.Nullable String context) {
    
    this.context = context;
    return this;
  }

  /**
   * First third of the system instruction — what the model is looking at. &#x60;null&#x60; uses the platform default.
   * @return context
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContext() {
    return context;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(@javax.annotation.Nullable String context) {
    this.context = context;
  }

  public Agent behaviour(@javax.annotation.Nullable String behaviour) {
    
    this.behaviour = behaviour;
    return this;
  }

  /**
   * Second third of the system instruction — how the model should act. &#x60;null&#x60; uses the platform default.
   * @return behaviour
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BEHAVIOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBehaviour() {
    return behaviour;
  }


  @JsonProperty(value = JSON_PROPERTY_BEHAVIOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBehaviour(@javax.annotation.Nullable String behaviour) {
    this.behaviour = behaviour;
  }

  public Agent spirit(@javax.annotation.Nullable String spirit) {
    
    this.spirit = spirit;
    return this;
  }

  /**
   * Last third of the system instruction — the tone it should take. &#x60;null&#x60; uses the platform default.
   * @return spirit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPIRIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpirit() {
    return spirit;
  }


  @JsonProperty(value = JSON_PROPERTY_SPIRIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpirit(@javax.annotation.Nullable String spirit) {
    this.spirit = spirit;
  }

  public Agent useHistory(@javax.annotation.Nonnull Boolean useHistory) {
    
    this.useHistory = useHistory;
    return this;
  }

  /**
   * When &#x60;false&#x60;, previous posts of the session are not replayed and do not widen the embedded query — every question is answered on its own.
   * @return useHistory
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USE_HISTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getUseHistory() {
    return useHistory;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_HISTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUseHistory(@javax.annotation.Nonnull Boolean useHistory) {
    this.useHistory = useHistory;
  }

  public Agent historySize(@javax.annotation.Nullable Integer historySize) {
    
    this.historySize = historySize;
    return this;
  }

  /**
   * Number of trailing posts replayed. &#x60;null&#x60; replays the whole session.
   * @return historySize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HISTORY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHistorySize() {
    return historySize;
  }


  @JsonProperty(value = JSON_PROPERTY_HISTORY_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHistorySize(@javax.annotation.Nullable Integer historySize) {
    this.historySize = historySize;
  }

  public Agent thinkingMode(@javax.annotation.Nonnull ThinkingModeEnum thinkingMode) {
    
    this.thinkingMode = thinkingMode;
    return this;
  }

  /**
   * Reasoning budget the model is asked to spend before answering.
   * @return thinkingMode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_THINKING_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ThinkingModeEnum getThinkingMode() {
    return thinkingMode;
  }


  @JsonProperty(value = JSON_PROPERTY_THINKING_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThinkingMode(@javax.annotation.Nonnull ThinkingModeEnum thinkingMode) {
    this.thinkingMode = thinkingMode;
  }

  public Agent temperature(@javax.annotation.Nullable Double temperature) {
    
    this.temperature = temperature;
    return this;
  }

  /**
   * Model temperature. &#x60;null&#x60; leaves the model default untouched. Temperature must match model range.
   * @return temperature
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTemperature() {
    return temperature;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemperature(@javax.annotation.Nullable Double temperature) {
    this.temperature = temperature;
  }

  public Agent rerankModel(@javax.annotation.Nullable String rerankModel) {
    
    this.rerankModel = rerankModel;
    return this;
  }

  /**
   * Model used for re-ranking, as advertised by &#x60;GET /v1/config/model&#x60;.
   * @return rerankModel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RERANK_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRerankModel() {
    return rerankModel;
  }


  @JsonProperty(value = JSON_PROPERTY_RERANK_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRerankModel(@javax.annotation.Nullable String rerankModel) {
    this.rerankModel = rerankModel;
  }

  public Agent baseModel(@javax.annotation.Nullable String baseModel) {
    
    this.baseModel = baseModel;
    return this;
  }

  /**
   * Model used to generate the answer, as advertised by &#x60;GET /v1/config/model&#x60;. &#x60;null&#x60; keeps whatever model the session was created with.
   * @return baseModel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BASE_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseModel() {
    return baseModel;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseModel(@javax.annotation.Nullable String baseModel) {
    this.baseModel = baseModel;
  }

  public Agent createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Creation timestamp (ISO-8601, UTC).
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Agent updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Last update timestamp (ISO-8601, UTC). Equal to &#x60;createdAt&#x60; on creation.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Agent _default(@javax.annotation.Nonnull Boolean _default) {
    
    this._default = _default;
    return this;
  }

  /**
   * Read-only. &#x60;true&#x60; on the single agent the platform falls back to when a query names none. At most one agent carries it.
   * @return _default
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDefault() {
    return _default;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDefault(@javax.annotation.Nonnull Boolean _default) {
    this._default = _default;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Agent agent = (Agent) o;
    return Objects.equals(this.id, agent.id) &&
        Objects.equals(this.name, agent.name) &&
        Objects.equals(this.description, agent.description) &&
        Objects.equals(this.lock, agent.lock) &&
        Objects.equals(this.topK, agent.topK) &&
        Objects.equals(this.rerank, agent.rerank) &&
        Objects.equals(this.rerankTopK, agent.rerankTopK) &&
        Objects.equals(this.context, agent.context) &&
        Objects.equals(this.behaviour, agent.behaviour) &&
        Objects.equals(this.spirit, agent.spirit) &&
        Objects.equals(this.useHistory, agent.useHistory) &&
        Objects.equals(this.historySize, agent.historySize) &&
        Objects.equals(this.thinkingMode, agent.thinkingMode) &&
        Objects.equals(this.temperature, agent.temperature) &&
        Objects.equals(this.rerankModel, agent.rerankModel) &&
        Objects.equals(this.baseModel, agent.baseModel) &&
        Objects.equals(this.createdAt, agent.createdAt) &&
        Objects.equals(this.updatedAt, agent.updatedAt) &&
        Objects.equals(this._default, agent._default);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, lock, topK, rerank, rerankTopK, context, behaviour, spirit, useHistory, historySize, thinkingMode, temperature, rerankModel, baseModel, createdAt, updatedAt, _default);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Agent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    lock: ").append(toIndentedString(lock)).append("\n");
    sb.append("    topK: ").append(toIndentedString(topK)).append("\n");
    sb.append("    rerank: ").append(toIndentedString(rerank)).append("\n");
    sb.append("    rerankTopK: ").append(toIndentedString(rerankTopK)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    behaviour: ").append(toIndentedString(behaviour)).append("\n");
    sb.append("    spirit: ").append(toIndentedString(spirit)).append("\n");
    sb.append("    useHistory: ").append(toIndentedString(useHistory)).append("\n");
    sb.append("    historySize: ").append(toIndentedString(historySize)).append("\n");
    sb.append("    thinkingMode: ").append(toIndentedString(thinkingMode)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    rerankModel: ").append(toIndentedString(rerankModel)).append("\n");
    sb.append("    baseModel: ").append(toIndentedString(baseModel)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

