/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Document used as context to produce a system answer.
 */
@JsonPropertyOrder({
  Attachment.JSON_PROPERTY_POST_ID,
  Attachment.JSON_PROPERTY_DOC_ID,
  Attachment.JSON_PROPERTY_SUMMARY,
  Attachment.JSON_PROPERTY_PAGES,
  Attachment.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Attachment {
  public static final String JSON_PROPERTY_POST_ID = "postId";
  @javax.annotation.Nonnull
  private String postId;

  public static final String JSON_PROPERTY_DOC_ID = "docId";
  @javax.annotation.Nonnull
  private UUID docId;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nonnull
  private String summary;

  public static final String JSON_PROPERTY_PAGES = "pages";
  @javax.annotation.Nonnull
  private List<Integer> pages = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public Attachment() {
  }

  public Attachment postId(@javax.annotation.Nonnull String postId) {
    
    this.postId = postId;
    return this;
  }

  /**
   * ID of the post (UUIDv4).
   * @return postId
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPostId() {
    return postId;
  }


  @JsonProperty(value = JSON_PROPERTY_POST_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPostId(@javax.annotation.Nonnull String postId) {
    this.postId = postId;
  }

  public Attachment docId(@javax.annotation.Nonnull UUID docId) {
    
    this.docId = docId;
    return this;
  }

  /**
   * ID of the document (UUIDv4).
   * @return docId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOC_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getDocId() {
    return docId;
  }


  @JsonProperty(value = JSON_PROPERTY_DOC_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocId(@javax.annotation.Nonnull UUID docId) {
    this.docId = docId;
  }

  public Attachment summary(@javax.annotation.Nonnull String summary) {
    
    this.summary = summary;
    return this;
  }

  /**
   * Summary of the document (markdown)
   * @return summary
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }

  public Attachment pages(@javax.annotation.Nonnull List<Integer> pages) {
    
    this.pages = pages;
    return this;
  }

  public Attachment addPagesItem(Integer pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<>();
    }
    this.pages.add(pagesItem);
    return this;
  }

  /**
   * Sorted list of page indexes (1-based) retrieved from this document. User endpoint /{id}/preview-urls get secured preview image of the page
   * @return pages
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Integer> getPages() {
    return pages;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPages(@javax.annotation.Nonnull List<Integer> pages) {
    this.pages = pages;
  }

  public Attachment metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public Attachment putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Metadata of the source document.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attachment attachment = (Attachment) o;
    return Objects.equals(this.postId, attachment.postId) &&
        Objects.equals(this.docId, attachment.docId) &&
        Objects.equals(this.summary, attachment.summary) &&
        Objects.equals(this.pages, attachment.pages) &&
        Objects.equals(this.metadata, attachment.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postId, docId, summary, pages, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attachment {\n");
    sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
    sb.append("    docId: ").append(toIndentedString(docId)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

