/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Patch a chunk. Only the fields present in the body are applied; the rest keep their current value. &#x60;id&#x60;, &#x60;documentId&#x60;, &#x60;corpusId&#x60; and &#x60;hash&#x60; are not patchable — a chunk cannot be moved to another document, and &#x60;hash&#x60; describes the text the pipeline embedded.
 */
@JsonPropertyOrder({
  ChunkUpdateRequest.JSON_PROPERTY_PAGES,
  ChunkUpdateRequest.JSON_PROPERTY_METADATA,
  ChunkUpdateRequest.JSON_PROPERTY_BODY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ChunkUpdateRequest {
  public static final String JSON_PROPERTY_PAGES = "pages";
  @javax.annotation.Nullable
  private List<Integer> pages = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_BODY = "body";
  @javax.annotation.Nullable
  private String body;

  public ChunkUpdateRequest() {
  }

  public ChunkUpdateRequest pages(@javax.annotation.Nullable List<Integer> pages) {
    
    this.pages = pages;
    return this;
  }

  public ChunkUpdateRequest addPagesItem(Integer pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<>();
    }
    this.pages.add(pagesItem);
    return this;
  }

  /**
   * Replacement page span: 1-based page numbers the chunk covers. Sent empty (&#x60;[]&#x60;) it clears the span, which is what a chunk belonging to no page in particular carries. Values are sorted and de-duplicated server-side, and a value below 1 is refused.
   * @return pages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getPages() {
    return pages;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPages(@javax.annotation.Nullable List<Integer> pages) {
    this.pages = pages;
  }

  public ChunkUpdateRequest metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public ChunkUpdateRequest putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Replacement metadata. This **replaces** the object rather than merging into it — send the full map you want stored, and &#x60;{}&#x60; to clear it.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }

  public ChunkUpdateRequest body(@javax.annotation.Nullable String body) {
    
    this.body = body;
    return this;
  }

  /**
   * Replacement chunk text, written to object storage. **The vector is not recomputed**: after this call the stored embedding still describes the previous text, so the chunk keeps being retrieved for the old wording and answers with the new one. That is the intended behaviour for a typo or a redaction, and the wrong tool for a rewrite — re-ingest the document for that.
   * @return body
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@javax.annotation.Nullable String body) {
    this.body = body;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChunkUpdateRequest chunkUpdateRequest = (ChunkUpdateRequest) o;
    return Objects.equals(this.pages, chunkUpdateRequest.pages) &&
        Objects.equals(this.metadata, chunkUpdateRequest.metadata) &&
        Objects.equals(this.body, chunkUpdateRequest.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pages, metadata, body);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChunkUpdateRequest {\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

