/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.springrest.models.Key;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paginated list of keys belonging to the caller&#39;s organization.
 */
@JsonPropertyOrder({
  KeyListResponse.JSON_PROPERTY_ORG_ID,
  KeyListResponse.JSON_PROPERTY_PAGE_INDEX,
  KeyListResponse.JSON_PROPERTY_ITEMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class KeyListResponse {
  public static final String JSON_PROPERTY_ORG_ID = "orgId";
  @javax.annotation.Nonnull
  private String orgId;

  public static final String JSON_PROPERTY_PAGE_INDEX = "pageIndex";
  @javax.annotation.Nullable
  private Integer pageIndex;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @javax.annotation.Nullable
  private List<Key> items = new ArrayList<>();

  public KeyListResponse() {
  }

  public KeyListResponse orgId(@javax.annotation.Nonnull String orgId) {
    
    this.orgId = orgId;
    return this;
  }

  /**
   * ID of the owning organization (UUIDv4).
   * @return orgId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORG_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrgId() {
    return orgId;
  }


  @JsonProperty(value = JSON_PROPERTY_ORG_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrgId(@javax.annotation.Nonnull String orgId) {
    this.orgId = orgId;
  }

  public KeyListResponse pageIndex(@javax.annotation.Nullable Integer pageIndex) {
    
    this.pageIndex = pageIndex;
    return this;
  }

  /**
   * Zero-based index of the returned page.
   * @return pageIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageIndex() {
    return pageIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageIndex(@javax.annotation.Nullable Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public KeyListResponse items(@javax.annotation.Nullable List<Key> items) {
    
    this.items = items;
    return this;
  }

  public KeyListResponse addItemsItem(Key itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Keys contained in this page.
   * @return items
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Key> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(@javax.annotation.Nullable List<Key> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyListResponse keyListResponse = (KeyListResponse) o;
    return Objects.equals(this.orgId, keyListResponse.orgId) &&
        Objects.equals(this.pageIndex, keyListResponse.pageIndex) &&
        Objects.equals(this.items, keyListResponse.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orgId, pageIndex, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyListResponse {\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

