/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.springrest.models.Post;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Pair of posts produced by a query: the user message and the corresponding system answer.
 */
@JsonPropertyOrder({
  PostItemResponse.JSON_PROPERTY_SESSION_ID,
  PostItemResponse.JSON_PROPERTY_QUERY,
  PostItemResponse.JSON_PROPERTY_ANSWER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class PostItemResponse {
  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nonnull
  private UUID sessionId;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nullable
  private Post query;

  public static final String JSON_PROPERTY_ANSWER = "answer";
  @javax.annotation.Nullable
  private Post answer;

  public PostItemResponse() {
  }

  public PostItemResponse sessionId(@javax.annotation.Nonnull UUID sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * ID of the session the posts belong to (UUIDv4).
   * @return sessionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionId(@javax.annotation.Nonnull UUID sessionId) {
    this.sessionId = sessionId;
  }

  public PostItemResponse query(@javax.annotation.Nullable Post query) {
    
    this.query = query;
    return this;
  }

  /**
   * User post (the query). &#x60;owner &#x3D; USER&#x60;.
   * @return query
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Post getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@javax.annotation.Nullable Post query) {
    this.query = query;
  }

  public PostItemResponse answer(@javax.annotation.Nullable Post answer) {
    
    this.answer = answer;
    return this;
  }

  /**
   * System post (the LLM answer). &#x60;owner &#x3D; SYSTEM&#x60;, with attachments pointing to the chunks used as context.
   * @return answer
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANSWER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Post getAnswer() {
    return answer;
  }


  @JsonProperty(value = JSON_PROPERTY_ANSWER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnswer(@javax.annotation.Nullable Post answer) {
    this.answer = answer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostItemResponse postItemResponse = (PostItemResponse) o;
    return Objects.equals(this.sessionId, postItemResponse.sessionId) &&
        Objects.equals(this.query, postItemResponse.query) &&
        Objects.equals(this.answer, postItemResponse.answer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, query, answer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostItemResponse {\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

