/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.springrest.models.Thread;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paginated list of threads. Echoes the filter that produced it.
 */
@JsonPropertyOrder({
  ThreadListResponse.JSON_PROPERTY_CORPUS_ID,
  ThreadListResponse.JSON_PROPERTY_USER_ID,
  ThreadListResponse.JSON_PROPERTY_METADATA,
  ThreadListResponse.JSON_PROPERTY_PAGE_INDEX,
  ThreadListResponse.JSON_PROPERTY_PAGE_SIZE,
  ThreadListResponse.JSON_PROPERTY_TOTAL,
  ThreadListResponse.JSON_PROPERTY_ITEMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ThreadListResponse {
  public static final String JSON_PROPERTY_CORPUS_ID = "corpusId";
  @javax.annotation.Nullable
  private UUID corpusId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_PAGE_INDEX = "pageIndex";
  @javax.annotation.Nonnull
  private Integer pageIndex;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  @javax.annotation.Nonnull
  private Integer pageSize;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nonnull
  private Long total;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @javax.annotation.Nullable
  private List<Thread> items = new ArrayList<>();

  public ThreadListResponse() {
  }

  public ThreadListResponse corpusId(@javax.annotation.Nullable UUID corpusId) {
    
    this.corpusId = corpusId;
    return this;
  }

  /**
   * Echo of the corpus filter, when the listing was filtered by corpus.
   * @return corpusId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CORPUS_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getCorpusId() {
    return corpusId;
  }


  @JsonProperty(value = JSON_PROPERTY_CORPUS_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorpusId(@javax.annotation.Nullable UUID corpusId) {
    this.corpusId = corpusId;
  }

  public ThreadListResponse userId(@javax.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Echo of the user filter, when the listing was filtered by user.
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }

  public ThreadListResponse metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public ThreadListResponse putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Echo of the metadata fragment used to filter the listing, when applicable.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }

  public ThreadListResponse pageIndex(@javax.annotation.Nonnull Integer pageIndex) {
    
    this.pageIndex = pageIndex;
    return this;
  }

  /**
   * Zero-based index of the returned page.
   * @return pageIndex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPageIndex() {
    return pageIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPageIndex(@javax.annotation.Nonnull Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public ThreadListResponse pageSize(@javax.annotation.Nonnull Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Number of items requested per page.
   * @return pageSize
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_SIZE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPageSize(@javax.annotation.Nonnull Integer pageSize) {
    this.pageSize = pageSize;
  }

  public ThreadListResponse total(@javax.annotation.Nonnull Long total) {
    
    this.total = total;
    return this;
  }

  /**
   * Total number of sessions matching the filter across every page.
   * @return total
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@javax.annotation.Nonnull Long total) {
    this.total = total;
  }

  public ThreadListResponse items(@javax.annotation.Nullable List<Thread> items) {
    
    this.items = items;
    return this;
  }

  public ThreadListResponse addItemsItem(Thread itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Threads contained in this page, newest first.
   * @return items
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Thread> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(@javax.annotation.Nullable List<Thread> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreadListResponse threadListResponse = (ThreadListResponse) o;
    return Objects.equals(this.corpusId, threadListResponse.corpusId) &&
        Objects.equals(this.userId, threadListResponse.userId) &&
        Objects.equals(this.metadata, threadListResponse.metadata) &&
        Objects.equals(this.pageIndex, threadListResponse.pageIndex) &&
        Objects.equals(this.pageSize, threadListResponse.pageSize) &&
        Objects.equals(this.total, threadListResponse.total) &&
        Objects.equals(this.items, threadListResponse.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(corpusId, userId, metadata, pageIndex, pageSize, total, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreadListResponse {\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

