/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Per-bucket create/remove deltas. For &#x60;storage&#x60;, the values are bytes rather than item counts.
 */
@JsonPropertyOrder({
  UsageDelta.JSON_PROPERTY_CREATED,
  UsageDelta.JSON_PROPERTY_REMOVED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class UsageDelta {
  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nonnull
  private Long created;

  public static final String JSON_PROPERTY_REMOVED = "removed";
  @javax.annotation.Nonnull
  private Long removed;

  public UsageDelta() {
  }

  public UsageDelta created(@javax.annotation.Nonnull Long created) {
    
    this.created = created;
    return this;
  }

  /**
   * Items whose &#x60;created_at&#x60; falls inside this bucket.
   * @return created
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@javax.annotation.Nonnull Long created) {
    this.created = created;
  }

  public UsageDelta removed(@javax.annotation.Nonnull Long removed) {
    
    this.removed = removed;
    return this;
  }

  /**
   * Items whose &#x60;deleted_at&#x60; falls inside this bucket (soft-deletes only — a hard delete leaves no trace).
   * @return removed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REMOVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getRemoved() {
    return removed;
  }


  @JsonProperty(value = JSON_PROPERTY_REMOVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRemoved(@javax.annotation.Nonnull Long removed) {
    this.removed = removed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageDelta usageDelta = (UsageDelta) o;
    return Objects.equals(this.created, usageDelta.created) &&
        Objects.equals(this.removed, usageDelta.removed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, removed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageDelta {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

