/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.springrest.models.UsageDelta;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Metrics for one calendar bucket of the series (UTC). Every bucket is complete; the one currently in progress is not reported.
 */
@JsonPropertyOrder({
  UsageBucket.JSON_PROPERTY_FROM,
  UsageBucket.JSON_PROPERTY_TO,
  UsageBucket.JSON_PROPERTY_TOKENS,
  UsageBucket.JSON_PROPERTY_CORPORA,
  UsageBucket.JSON_PROPERTY_SESSIONS,
  UsageBucket.JSON_PROPERTY_POSTS,
  UsageBucket.JSON_PROPERTY_STORAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class UsageBucket {
  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private OffsetDateTime from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nonnull
  private OffsetDateTime to;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @javax.annotation.Nonnull
  private Long tokens;

  public static final String JSON_PROPERTY_CORPORA = "corpora";
  @javax.annotation.Nullable
  private UsageDelta corpora;

  public static final String JSON_PROPERTY_SESSIONS = "sessions";
  @javax.annotation.Nonnull
  private UsageDelta sessions;

  public static final String JSON_PROPERTY_POSTS = "posts";
  @javax.annotation.Nonnull
  private UsageDelta posts;

  public static final String JSON_PROPERTY_STORAGE = "storage";
  @javax.annotation.Nonnull
  private UsageDelta storage;

  public UsageBucket() {
  }

  public UsageBucket from(@javax.annotation.Nonnull OffsetDateTime from) {
    
    this.from = from;
    return this;
  }

  /**
   * Inclusive start of the bucket (ISO-8601, UTC).
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull OffsetDateTime from) {
    this.from = from;
  }

  public UsageBucket to(@javax.annotation.Nonnull OffsetDateTime to) {
    
    this.to = to;
    return this;
  }

  /**
   * Exclusive end of the bucket (ISO-8601, UTC). Equal to the &#x60;from&#x60; of the next bucket.
   * @return to
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@javax.annotation.Nonnull OffsetDateTime to) {
    this.to = to;
  }

  public UsageBucket tokens(@javax.annotation.Nonnull Long tokens) {
    
    this.tokens = tokens;
    return this;
  }

  /**
   * Tokens produced inside this bucket. At organization and user scope, posts **and** documents; at corpus scope, posts only.
   * @return tokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTokens() {
    return tokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokens(@javax.annotation.Nonnull Long tokens) {
    this.tokens = tokens;
  }

  public UsageBucket corpora(@javax.annotation.Nullable UsageDelta corpora) {
    
    this.corpora = corpora;
    return this;
  }

  /**
   * Corpus deltas for this bucket. Populated at organization scope only; &#x60;null&#x60; at corpus and user scopes, as it is at the top level.
   * @return corpora
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CORPORA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UsageDelta getCorpora() {
    return corpora;
  }


  @JsonProperty(value = JSON_PROPERTY_CORPORA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorpora(@javax.annotation.Nullable UsageDelta corpora) {
    this.corpora = corpora;
  }

  public UsageBucket sessions(@javax.annotation.Nonnull UsageDelta sessions) {
    
    this.sessions = sessions;
    return this;
  }

  /**
   * Session deltas for this bucket.
   * @return sessions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UsageDelta getSessions() {
    return sessions;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessions(@javax.annotation.Nonnull UsageDelta sessions) {
    this.sessions = sessions;
  }

  public UsageBucket posts(@javax.annotation.Nonnull UsageDelta posts) {
    
    this.posts = posts;
    return this;
  }

  /**
   * Post deltas for this bucket.
   * @return posts
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POSTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UsageDelta getPosts() {
    return posts;
  }


  @JsonProperty(value = JSON_PROPERTY_POSTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPosts(@javax.annotation.Nonnull UsageDelta posts) {
    this.posts = posts;
  }

  public UsageBucket storage(@javax.annotation.Nonnull UsageDelta storage) {
    
    this.storage = storage;
    return this;
  }

  /**
   * Storage deltas for this bucket, in **bytes** — not item counts.
   * @return storage
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STORAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UsageDelta getStorage() {
    return storage;
  }


  @JsonProperty(value = JSON_PROPERTY_STORAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStorage(@javax.annotation.Nonnull UsageDelta storage) {
    this.storage = storage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageBucket usageBucket = (UsageBucket) o;
    return Objects.equals(this.from, usageBucket.from) &&
        Objects.equals(this.to, usageBucket.to) &&
        Objects.equals(this.tokens, usageBucket.tokens) &&
        Objects.equals(this.corpora, usageBucket.corpora) &&
        Objects.equals(this.sessions, usageBucket.sessions) &&
        Objects.equals(this.posts, usageBucket.posts) &&
        Objects.equals(this.storage, usageBucket.storage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, tokens, corpora, sessions, posts, storage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageBucket {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    corpora: ").append(toIndentedString(corpora)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("    posts: ").append(toIndentedString(posts)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

