/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * WidgetQueryResponse
 */
@JsonPropertyOrder({
  WidgetQueryResponse.JSON_PROPERTY_TIMESTAMP,
  WidgetQueryResponse.JSON_PROPERTY_SESSION_ID,
  WidgetQueryResponse.JSON_PROPERTY_QUERY,
  WidgetQueryResponse.JSON_PROPERTY_BODY,
  WidgetQueryResponse.JSON_PROPERTY_ATTACHMENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WidgetQueryResponse {
  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_SESSION_ID = "sessionId";
  @javax.annotation.Nullable
  private UUID sessionId;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nullable
  private String query;

  public static final String JSON_PROPERTY_BODY = "body";
  @javax.annotation.Nullable
  private String body;

  public static final String JSON_PROPERTY_ATTACHMENT = "attachment";
  @javax.annotation.Nullable
  private Integer attachment;

  public WidgetQueryResponse() {
  }

  public WidgetQueryResponse timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Timestamp when the answer was generated
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public WidgetQueryResponse sessionId(@javax.annotation.Nullable UUID sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Id of the session the query belongs to
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable UUID sessionId) {
    this.sessionId = sessionId;
  }

  public WidgetQueryResponse query(@javax.annotation.Nullable String query) {
    
    this.query = query;
    return this;
  }

  /**
   * The user query that was submitted
   * @return query
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@javax.annotation.Nullable String query) {
    this.query = query;
  }

  public WidgetQueryResponse body(@javax.annotation.Nullable String body) {
    
    this.body = body;
    return this;
  }

  /**
   * The AI-generated answer, may include markdown and source citations
   * @return body
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@javax.annotation.Nullable String body) {
    this.body = body;
  }

  public WidgetQueryResponse attachment(@javax.annotation.Nullable Integer attachment) {
    
    this.attachment = attachment;
    return this;
  }

  /**
   * Number of source document chunks cited in the answer
   * @return attachment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTACHMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAttachment() {
    return attachment;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTACHMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttachment(@javax.annotation.Nullable Integer attachment) {
    this.attachment = attachment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetQueryResponse widgetQueryResponse = (WidgetQueryResponse) o;
    return Objects.equals(this.timestamp, widgetQueryResponse.timestamp) &&
        Objects.equals(this.sessionId, widgetQueryResponse.sessionId) &&
        Objects.equals(this.query, widgetQueryResponse.query) &&
        Objects.equals(this.body, widgetQueryResponse.body) &&
        Objects.equals(this.attachment, widgetQueryResponse.attachment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, sessionId, query, body, attachment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetQueryResponse {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

