/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * WidgetSessionRequest
 */
@JsonPropertyOrder({
  WidgetSessionRequest.JSON_PROPERTY_WIDGET_NAME,
  WidgetSessionRequest.JSON_PROPERTY_DISPLAY_NAME,
  WidgetSessionRequest.JSON_PROPERTY_CORPUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WidgetSessionRequest {
  public static final String JSON_PROPERTY_WIDGET_NAME = "widgetName";
  @javax.annotation.Nonnull
  private String widgetName;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nullable
  private String displayName;

  public static final String JSON_PROPERTY_CORPUS = "corpus";
  @javax.annotation.Nonnull
  private List<UUID> corpus = new ArrayList<>();

  public WidgetSessionRequest() {
  }

  public WidgetSessionRequest widgetName(@javax.annotation.Nonnull String widgetName) {
    
    this.widgetName = widgetName;
    return this;
  }

  /**
   * Name of the widget
   * @return widgetName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WIDGET_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWidgetName() {
    return widgetName;
  }


  @JsonProperty(value = JSON_PROPERTY_WIDGET_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWidgetName(@javax.annotation.Nonnull String widgetName) {
    this.widgetName = widgetName;
  }

  public WidgetSessionRequest displayName(@javax.annotation.Nullable String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * Display name of the session (session history). When not set, a default display name is set from Widget name
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }

  public WidgetSessionRequest corpus(@javax.annotation.Nonnull List<UUID> corpus) {
    
    this.corpus = corpus;
    return this;
  }

  public WidgetSessionRequest addCorpusItem(UUID corpusItem) {
    if (this.corpus == null) {
      this.corpus = new ArrayList<>();
    }
    this.corpus.add(corpusItem);
    return this;
  }

  /**
   * List of Corpus UID used by the session. Check Corpus domain to learn how init a Corpus
   * @return corpus
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CORPUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<UUID> getCorpus() {
    return corpus;
  }


  @JsonProperty(value = JSON_PROPERTY_CORPUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCorpus(@javax.annotation.Nonnull List<UUID> corpus) {
    this.corpus = corpus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetSessionRequest widgetSessionRequest = (WidgetSessionRequest) o;
    return Objects.equals(this.widgetName, widgetSessionRequest.widgetName) &&
        Objects.equals(this.displayName, widgetSessionRequest.displayName) &&
        Objects.equals(this.corpus, widgetSessionRequest.corpus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(widgetName, displayName, corpus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetSessionRequest {\n");
    sb.append("    widgetName: ").append(toIndentedString(widgetName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    corpus: ").append(toIndentedString(corpus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

