/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * WidgetAttachmentPage
 */
@JsonPropertyOrder({
  WidgetAttachmentPage.JSON_PROPERTY_INDEX,
  WidgetAttachmentPage.JSON_PROPERTY_PREVIEW_SMALL_URL,
  WidgetAttachmentPage.JSON_PROPERTY_PREVIEW_SMALL_LARGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WidgetAttachmentPage {
  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nonnull
  private Integer index;

  public static final String JSON_PROPERTY_PREVIEW_SMALL_URL = "previewSmallUrl";
  @javax.annotation.Nullable
  private String previewSmallUrl;

  public static final String JSON_PROPERTY_PREVIEW_SMALL_LARGE = "previewSmallLarge";
  @javax.annotation.Nullable
  private String previewSmallLarge;

  public WidgetAttachmentPage() {
  }

  public WidgetAttachmentPage index(@javax.annotation.Nonnull Integer index) {
    
    this.index = index;
    return this;
  }

  /**
   * Index of the page (1-based)
   * @return index
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIndex(@javax.annotation.Nonnull Integer index) {
    this.index = index;
  }

  public WidgetAttachmentPage previewSmallUrl(@javax.annotation.Nullable String previewSmallUrl) {
    
    this.previewSmallUrl = previewSmallUrl;
    return this;
  }

  /**
   * Get previewSmallUrl
   * @return previewSmallUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIEW_SMALL_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviewSmallUrl() {
    return previewSmallUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIEW_SMALL_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviewSmallUrl(@javax.annotation.Nullable String previewSmallUrl) {
    this.previewSmallUrl = previewSmallUrl;
  }

  public WidgetAttachmentPage previewSmallLarge(@javax.annotation.Nullable String previewSmallLarge) {
    
    this.previewSmallLarge = previewSmallLarge;
    return this;
  }

  /**
   * Get previewSmallLarge
   * @return previewSmallLarge
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIEW_SMALL_LARGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviewSmallLarge() {
    return previewSmallLarge;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIEW_SMALL_LARGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviewSmallLarge(@javax.annotation.Nullable String previewSmallLarge) {
    this.previewSmallLarge = previewSmallLarge;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetAttachmentPage widgetAttachmentPage = (WidgetAttachmentPage) o;
    return Objects.equals(this.index, widgetAttachmentPage.index) &&
        Objects.equals(this.previewSmallUrl, widgetAttachmentPage.previewSmallUrl) &&
        Objects.equals(this.previewSmallLarge, widgetAttachmentPage.previewSmallLarge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, previewSmallUrl, previewSmallLarge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetAttachmentPage {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    previewSmallUrl: ").append(toIndentedString(previewSmallUrl)).append("\n");
    sb.append("    previewSmallLarge: ").append(toIndentedString(previewSmallLarge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

