/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.springrest.models.SessionMessage;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * WidgetSessionResponseItem
 */
@JsonPropertyOrder({
  WidgetSessionResponseItem.JSON_PROPERTY_CREATED_AT,
  WidgetSessionResponseItem.JSON_PROPERTY_MESSAGES,
  WidgetSessionResponseItem.JSON_PROPERTY_SESSION_UUID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WidgetSessionResponseItem {
  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @javax.annotation.Nullable
  private List<SessionMessage> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_SESSION_UUID = "sessionUuid";
  @javax.annotation.Nullable
  private String sessionUuid;

  public WidgetSessionResponseItem() {
  }

  public WidgetSessionResponseItem createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public WidgetSessionResponseItem messages(@javax.annotation.Nullable List<SessionMessage> messages) {
    
    this.messages = messages;
    return this;
  }

  public WidgetSessionResponseItem addMessagesItem(SessionMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SessionMessage> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessages(@javax.annotation.Nullable List<SessionMessage> messages) {
    this.messages = messages;
  }

  public WidgetSessionResponseItem sessionUuid(@javax.annotation.Nullable String sessionUuid) {
    
    this.sessionUuid = sessionUuid;
    return this;
  }

  /**
   * Get sessionUuid
   * @return sessionUuid
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_UUID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionUuid() {
    return sessionUuid;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_UUID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionUuid(@javax.annotation.Nullable String sessionUuid) {
    this.sessionUuid = sessionUuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetSessionResponseItem widgetSessionResponseItem = (WidgetSessionResponseItem) o;
    return Objects.equals(this.createdAt, widgetSessionResponseItem.createdAt) &&
        Objects.equals(this.messages, widgetSessionResponseItem.messages) &&
        Objects.equals(this.sessionUuid, widgetSessionResponseItem.sessionUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, messages, sessionUuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetSessionResponseItem {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    sessionUuid: ").append(toIndentedString(sessionUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

