/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.springrest.models.WidgetAttachmentPage;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * WidgetAttachment
 */
@JsonPropertyOrder({
  WidgetAttachment.JSON_PROPERTY_DOC_ID,
  WidgetAttachment.JSON_PROPERTY_SUMMARY,
  WidgetAttachment.JSON_PROPERTY_PAGES,
  WidgetAttachment.JSON_PROPERTY_METADATA,
  WidgetAttachment.JSON_PROPERTY_PREVIEW_EXPIRATION_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WidgetAttachment {
  public static final String JSON_PROPERTY_DOC_ID = "docId";
  @javax.annotation.Nonnull
  private UUID docId;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nonnull
  private String summary;

  public static final String JSON_PROPERTY_PAGES = "pages";
  @javax.annotation.Nonnull
  private List<WidgetAttachmentPage> pages = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_PREVIEW_EXPIRATION_DATE = "previewExpirationDate";
  @javax.annotation.Nullable
  private OffsetDateTime previewExpirationDate;

  public WidgetAttachment() {
  }

  public WidgetAttachment docId(@javax.annotation.Nonnull UUID docId) {
    
    this.docId = docId;
    return this;
  }

  /**
   * ID of the document (UUIDv4).
   * @return docId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOC_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getDocId() {
    return docId;
  }


  @JsonProperty(value = JSON_PROPERTY_DOC_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocId(@javax.annotation.Nonnull UUID docId) {
    this.docId = docId;
  }

  public WidgetAttachment summary(@javax.annotation.Nonnull String summary) {
    
    this.summary = summary;
    return this;
  }

  /**
   * Summary of the document (markdown)
   * @return summary
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }

  public WidgetAttachment pages(@javax.annotation.Nonnull List<WidgetAttachmentPage> pages) {
    
    this.pages = pages;
    return this;
  }

  public WidgetAttachment addPagesItem(WidgetAttachmentPage pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<>();
    }
    this.pages.add(pagesItem);
    return this;
  }

  /**
   * Sorted list of page (1-based) retrieved from this document with preview image url.
   * @return pages
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WidgetAttachmentPage> getPages() {
    return pages;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPages(@javax.annotation.Nonnull List<WidgetAttachmentPage> pages) {
    this.pages = pages;
  }

  public WidgetAttachment metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public WidgetAttachment putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Metadata of the source document.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }

  public WidgetAttachment previewExpirationDate(@javax.annotation.Nullable OffsetDateTime previewExpirationDate) {
    
    this.previewExpirationDate = previewExpirationDate;
    return this;
  }

  /**
   * Get previewExpirationDate
   * @return previewExpirationDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIEW_EXPIRATION_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPreviewExpirationDate() {
    return previewExpirationDate;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIEW_EXPIRATION_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviewExpirationDate(@javax.annotation.Nullable OffsetDateTime previewExpirationDate) {
    this.previewExpirationDate = previewExpirationDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetAttachment widgetAttachment = (WidgetAttachment) o;
    return Objects.equals(this.docId, widgetAttachment.docId) &&
        Objects.equals(this.summary, widgetAttachment.summary) &&
        Objects.equals(this.pages, widgetAttachment.pages) &&
        Objects.equals(this.metadata, widgetAttachment.metadata) &&
        Objects.equals(this.previewExpirationDate, widgetAttachment.previewExpirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docId, summary, pages, metadata, previewExpirationDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetAttachment {\n");
    sb.append("    docId: ").append(toIndentedString(docId)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    previewExpirationDate: ").append(toIndentedString(previewExpirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

