/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.api;

import com.verbatim.client.springrest.models.AckResponse;
import com.verbatim.client.springrest.models.Agent;
import com.verbatim.client.springrest.models.AgentCreateRequest;
import com.verbatim.client.springrest.models.AgentListResponse;
import com.verbatim.client.springrest.models.AgentUpdateRequest;
import com.verbatim.client.springrest.models.Error;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgentApi
 */
@Disabled
class AgentApiTest {

    private final AgentApi api = new AgentApi();

    
    /**
     * Create an agent
     *
     * Create a custom agent owned by your organization.  Only &#x60;name&#x60; is required — the smallest useful body is &#x60;{\&quot;name\&quot;: \&quot;...\&quot;}&#x60;, which produces an agent identical in behaviour to the platform default and free to diverge from it later. Every field you leave out either takes its column default (&#x60;topK&#x60; 5, &#x60;rerank&#x60; true, &#x60;useHistory&#x60; true, &#x60;thinkingMode&#x60; HIGH) or stays unset and tracks the platform value.  &#x60;name&#x60; must be free: not one of your own agents&#39; names, and not one carried by a platform agent (&#x60;lock: true&#x60;) either — both answer &#x60;409&#x60;. Core agents appear in your listing, so &#x60;Verbatim Default&#x60; there and &#x60;Verbatim Default&#x60; of your own would be two entries you could only tell apart by &#x60;lock&#x60;. Names are compared exactly, so &#x60;Support&#x60; and &#x60;support&#x60; are two names and &#x60;Verbatim Default v2&#x60; is free. Deleting an agent puts its name back into circulation.  &#x60;rerankModel&#x60; and &#x60;baseModel&#x60; are checked against &#x60;GET /v1/config/model&#x60; here rather than at query time, so a typo is a &#x60;400&#x60; on this request instead of a failure on every query the agent later runs.  The result is always &#x60;lock: false&#x60; and &#x60;default: false&#x60;. Core agents are seeded by the platform and cannot be created over the API. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void create3Test() {
        AgentCreateRequest agentCreateRequest = null;

        Agent response = api.create3(agentCreateRequest);

        // TODO: test validations
    }
    
    /**
     * Delete an agent
     *
     * Delete a custom agent. From here on it is gone: absent from &#x60;GET /v1/agent/&#x60;, &#x60;404&#x60; on get, update and delete, and &#x60;404&#x60; on any query naming it — a deleted agent is indistinguishable from one that never existed.  What it does **not** do is rewrite the past. Answers already produced under this agent keep naming it in their &#x60;agentId&#x60;, so a conversation stays readable exactly as it happened. Deleting an agent changes what you can use from now on, not what already ran.  Sessions are unaffected: an agent is resolved per query, so a conversation that used this one simply carries on under the platform default.  Its &#x60;name&#x60; goes back into circulation, so a replacement can be created under the same name straight away.  Core agents (&#x60;lock: true&#x60;) cannot be deleted — that answers &#x60;400&#x60;. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void delete4Test() {
        UUID agentId = null;

        AckResponse response = api.delete4(agentId);

        // TODO: test validations
    }
    
    /**
     * Get an agent
     *
     * Fetch one agent by its identifier — yours or a core one.  An id belonging to another organization answers &#x60;404&#x60;, the same as an id that does not exist: the two are deliberately indistinguishable. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void get4Test() {
        UUID agentId = null;

        Agent response = api.get4(agentId);

        // TODO: test validations
    }
    
    /**
     * List agents
     *
     * Paginate every agent your organization can query with: the platform&#39;s core agents merged with your own custom ones, **core first**, then by name.  There is no separate endpoint for the core catalogue — the merge is the point. Tell the two apart by &#x60;lock&#x60;: &#x60;true&#x60; is a platform agent you can read and use but not modify. A brand-new organization sees six of them, one per use case, and the single agent carrying &#x60;default: true&#x60; is the one a query that names no agent runs on. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void list2Test() {
        Integer pageSize = null;
        Integer pageIndex = null;

        AgentListResponse response = api.list2(pageSize, pageIndex);

        // TODO: test validations
    }
    
    /**
     * Update an agent
     *
     * Patch a custom agent. Fields absent from the body keep their current value.  Because \&quot;absent\&quot; already means \&quot;leave alone\&quot;, it cannot also mean \&quot;put this back to the platform default\&quot; — that is what &#x60;reset&#x60; is for. List the nullable fields you want un-set and they go back to tracking the platform value:  &#x60;&#x60;&#x60;json { \&quot;topK\&quot;: 12, \&quot;reset\&quot;: [\&quot;spirit\&quot;, \&quot;temperature\&quot;] } &#x60;&#x60;&#x60;  &#x60;reset&#x60; runs after the rest of the body, so a field named in both ends up cleared.  Renaming onto a name another of your agents holds, or one a platform agent carries, answers &#x60;409&#x60;. Sending this agent&#39;s own current name does not — an unchanged name is not a rename, so a client that echoes the whole object back is unaffected.  Core agents (&#x60;lock: true&#x60;) belong to the platform and every organization sees the same row — patching one answers &#x60;400&#x60;. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void update4Test() {
        UUID agentId = null;
        AgentUpdateRequest agentUpdateRequest = null;

        Agent response = api.update4(agentId, agentUpdateRequest);

        // TODO: test validations
    }
    
}
