/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.api;

import com.verbatim.client.springrest.models.AckResponse;
import com.verbatim.client.springrest.models.CheckResponse;
import com.verbatim.client.springrest.models.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicApi
 */
@Disabled
class PublicApiTest {

    private final PublicApi api = new PublicApi();

    
    /**
     * Assert an email free from registration
     *
     * Check if the email is unknown and can be go throw signin process
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void assertEmailTest() {
        String email = null;
        String turnstileToken = null;
        String languageCode = null;

        AckResponse response = api.assertEmail(email, turnstileToken, languageCode);

        // TODO: test validations
    }
    
    /**
     * Deep health check
     *
     * Probe every subsystem the platform depends on and report each outcome:  - **S3** — read an object back from the archive storage - **DB** — run a query on a pooled connection - **LLM** — send a prompt to the inference endpoint and require an answer  Every probe runs on every call, so one failure never hides another. The response is &#x60;200&#x60; when all of them pass and &#x60;500&#x60; as soon as one fails, which is the signal a monitoring tool alerts on; the body names the failing subsystem and carries its reason.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void checkTest() {

        CheckResponse response = api.check();

        // TODO: test validations
    }
    
    /**
     * Assert email verification code
     *
     * Assert the code sent to the email
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void checkVerificationCodeTest() {
        String email = null;
        String code = null;
        String turnstileToken = null;

        AckResponse response = api.checkVerificationCode(email, code, turnstileToken);

        // TODO: test validations
    }
    
    /**
     * Basic ping
     *
     * Simple open API to ping platform. Easy to use for an healthy check
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void pingTest() {

        api.ping();

        // TODO: test validations
    }
    
}
