/*
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.api;

import com.verbatim.client.springrest.models.Error;
import java.util.UUID;
import com.verbatim.client.springrest.models.Usage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsageApi
 */
@Disabled
class UsageApiTest {

    private final UsageApi api = new UsageApi();

    
    /**
     * Organization usage
     *
     * Return the aggregated usage report for the caller&#39;s organization over a rolling timeframe.  Each dimension is reported as: - **tokens** — &#x60;total&#x60; (lifetime, soft-deleted included) and &#x60;inPeriod&#x60; (window). At organization scope this sums &#x60;post.token&#x60; AND &#x60;document.token&#x60; (vectorization tokens are billed at organization level). - **corpora / sessions / posts / storage** — &#x60;total&#x60;, &#x60;created&#x60; (in window), &#x60;removed&#x60; (in window). - **storage** values are bytes.  The &#x60;timeframe&#x60; parameter selects a rolling window ending at &#x60;timestamp&#x60;:  - &#x60;Day&#x60; — last 24 hours - &#x60;Week&#x60; — last 7 days - &#x60;Month&#x60; — last 30 days - &#x60;Year&#x60; — last 365 days  The window is half-open: &#x60;from&#x60; inclusive, &#x60;to&#x60; exclusive. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void usageTest() {
        String timeframe = null;

        Usage response = api.usage(timeframe);

        // TODO: test validations
    }
    
    /**
     * Corpus usage
     *
     * Return the aggregated usage report for a single corpus over a rolling timeframe.  Differences with the organization-scope report: - **tokens** sums &#x60;post.token&#x60; only — vectorization tokens (&#x60;document.token&#x60;) are reported only at organization scope, because they are billed against the org. - **corpora** is &#x60;null&#x60; — cardinality is always 1 at corpus scope.  Sessions, posts and storage are restricted to the requested corpus. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void usageByCorpusTest() {
        UUID corpusId = null;
        String timeframe = null;

        Usage response = api.usageByCorpus(corpusId, timeframe);

        // TODO: test validations
    }
    
    /**
     * User usage
     *
     * Return the aggregated usage report for a single user within the caller&#39;s organization over a rolling timeframe.  Scope: - **tokens** sums &#x60;post.token&#x60; of sessions where &#x60;session.user_id &#x3D; userId&#x60; AND &#x60;document.token&#x60; of documents where &#x60;document.user_id &#x3D; userId&#x60;, both restricted to corpora of &#x60;orgId&#x60;. - **sessions** counts distinct sessions owned by &#x60;userId&#x60; in the organization. - **posts** counts posts in those sessions. - **storage** sums &#x60;document.size&#x60; of documents uploaded by &#x60;userId&#x60; in the organization. - **corpora** is &#x60;null&#x60; — cardinality is not meaningful at user scope.  Soft-deleted rows count toward lifetime totals; the &#x60;removed&#x60; deltas detect cleanup. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void usageByUserTest() {
        String userId = null;
        String timeframe = null;

        Usage response = api.usageByUser(userId, timeframe);

        // TODO: test validations
    }
    
}
