/*
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.springrest.api;

import com.verbatim.client.springrest.models.Error;
import java.util.UUID;
import com.verbatim.client.springrest.models.WidgetAttachmentResponse;
import com.verbatim.client.springrest.models.WidgetMessageResponse;
import com.verbatim.client.springrest.models.WidgetPostsResponse;
import com.verbatim.client.springrest.models.WidgetQueryResponse;
import com.verbatim.client.springrest.models.WidgetSessionRequest;
import com.verbatim.client.springrest.models.WidgetSessionRequestBody;
import com.verbatim.client.springrest.models.WidgetSessionResponse;
import com.verbatim.client.springrest.models.WidgetSessionResponseLegacy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WidgetApi
 */
@Disabled
class WidgetApiTest {

    private final WidgetApi api = new WidgetApi();

    
    /**
     * Get source attachments of a post
     *
     * Returns every source document that the AI cited when generating a SYSTEM post. For each document the response includes its summary, metadata, and **presigned preview URLs** for every page that was actually retrieved (1-based index). Two sizes are provided per page — &#x60;previewSmallUrl&#x60; (SMALL) and &#x60;previewSmallLarge&#x60; (MEDIUM) — so the widget can render a thumbnail and a full-size lightbox view without additional round-trips. All presigned URLs share the same &#x60;previewExpirationDate&#x60;; refresh by calling this endpoint again after expiry. The post must belong to the organisation identified by the Access Token.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void attachmentTest() {
        UUID postId = null;

        WidgetAttachmentResponse response = api.attachment(postId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getSessionTest() {
        String lang = null;
        String cid = null;
        UUID sid = null;

        WidgetSessionResponseLegacy response = api.getSession(lang, cid, sid);

        // TODO: test validations
    }
    
    /**
     * Init a session
     *
     * Init a new session with a context : name and a search context, defined by a list of Corpus UID
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void initTest() {
        WidgetSessionRequest widgetSessionRequest = null;

        WidgetSessionResponse response = api.init(widgetSessionRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postMessageTest() {
        String lang = null;
        String cid = null;
        UUID sid = null;
        WidgetSessionRequestBody widgetSessionRequestBody = null;

        WidgetMessageResponse response = api.postMessage(lang, cid, sid, widgetSessionRequestBody);

        // TODO: test validations
    }
    
    /**
     * List posts in a session
     *
     * Returns the full chronological history of a session — both user queries (&#x60;owner: USER&#x60;) and AI answers (&#x60;owner: SYSTEM&#x60;). Each item includes the message text, language, timestamp, and the number of source document chunks cited (&#x60;attachment&#x60; count). The session must belong to the organisation identified by the Access Token.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void postsTest() {
        UUID sessionId = null;

        WidgetPostsResponse response = api.posts(sessionId);

        // TODO: test validations
    }
    
    /**
     * Post a query in a session
     *
     * User query is posted in the session. AI backend system answer to this query
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void queryTest() {
        UUID sessionId = null;
        String query = null;
        String lang = null;

        WidgetQueryResponse response = api.query(sessionId, query, lang);

        // TODO: test validations
    }
    
}
